version: '2.1'

services:
  db:
    image: mysql:8.0
    container_name: microservice-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: microservice-phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
